### ISSUE TITLE
想问问大佬主题预览图中的正文部分字体是什么？

### ISSUE THREAD

**Issue by YYHCOPPOLO** [mindstudy/siyuan-themes-concise-light#1]
如题，感谢大佬解答

**Comment by mindstudy** [comment]
主题预览图字体发生过变动。

如果是最初两三个版本，是衬线字体 FZYouSongS 方正悠宋简，适合长文档长时间阅读。

现在的是无衬线字体 PingFang SC 苹方简。无衬线字体易于识别，设计感强，是很多移动设备默认字体。

**Comment by YYHCOPPOLO** [comment]
感谢大佬回复，能再问一下这个方正悠宋的字体文件吗，因为我在方正官网下载的方正悠宋在思源里都无法生效，无论是通过改css还是思源自带修改都不行，重启也试过了，方正屏显雅宋倒是正常，就很迷惑

**Comment by mindstudy** [comment]
多几个下载渠道试试，另外Word也看看能不能生效

**Comment by hscui** [comment]
> 

我的也是方正下载的，无法显示，目前好像用的是黑体？或者是雅黑之类的；标题到是正常显示雅宋，我怀疑是因为悠宋粗细不同字号太多了？所以需要所有的字号都下载安装？还没尝试。

**Comment by YYHCOPPOLO** [comment]
> > 
> 
> 我的也是方正下载的，无法显示，目前好像用的是黑体？或者是雅黑之类的；标题到是正常显示雅宋，我怀疑是因为悠宋粗细不同字号太多了？所以需要所有的字号都下载安装？还没尝试。

我知道问题了，要在CSS里打上全称，如 "方正悠宋 508R" ，不过在windows思源里渲染也不好看，我现在放弃了，可能是2K的屏幕问题。

**Comment by hscui** [comment]
> 

谢谢，我去试试。不过我个人觉得最好还是用Free字体，比如思源字体吧。
