### ISSUE TITLE
在鼠标放到引用的内容上，如果显示不全，不会出现滚动条

### ISSUE THREAD

**Issue by bengirl2021** [mindstudy/siyuan-themes-concise-light#10]
![image](https://user-images.githubusercontent.com/101393495/169640863-9f2bb51d-5e60-4bb7-95f4-fc87512040ab.png)
原版的亮色主题是会的，否则这样的话还得把框拖上来才能看到下面的内容，不能直接滚动

**Comment by mindstudy** [comment]
Concise 主题下，如果鼠标或光标焦点不在当前界面上（比如说上图的浮窗），默认是隐藏滚动条的，这样设计是为了视觉上更清爽。

只要把鼠标移到浮窗上，有滚动条的窗口就会出现滚动条。

**Comment by bengirl2021** [comment]
我的材料是可以滚动的，在原版亮主题是可以的，但是在这里我把鼠标放上去甚至点击都不可以滚动



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月21日(周六) 下午4:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [mindstudy/siyuan-themes-concise-light] 在鼠标放到引用的内容上，如果显示不全，不会出现滚动条 (Issue #10)




 
Concise 主题下，如果鼠标或光标焦点不在当前界面上（比如说上图的浮窗），默认是隐藏滚动条的，这样设计是为了视觉上更清爽。
 
只要把鼠标移到浮窗上，有滚动条的窗口就会出现滚动条。

**Comment by bengirl2021** [comment]
> Concise 主题下，如果鼠标或光标焦点不在当前界面上（比如说上图的浮窗），默认是隐藏滚动条的，这样设计是为了视觉上更清爽。
> 
> 只要把鼠标移到浮窗上，有滚动条的窗口就会出现滚动条。

我的材料是可以滚动的，在原版亮主题是可以的，但是在这里我把鼠标放上去甚至点击都不可以滚动

**Comment by bengirl2021** [comment]
https://user-images.githubusercontent.com/101393495/169646444-1cc2d395-87e3-498c-bab8-976fa3566a9a.mp4
我不是很懂css，
我个人主观判断这个主题是否加滚动条的逻辑是：如果这个界面的高度，小于屏幕的高度，那就不加滚动条，但有时候界面高度小于屏幕高度也得加滚动条，类似这样。（css小白看法哈哈哈哈）
![image](https://user-images.githubusercontent.com/101393495/169646524-7d18f30d-beec-471e-82fc-bab134869ddd.png)

**Comment by mindstudy** [comment]
大概知道原因了，浮窗滚动条的鼠标激活区域，在面包屑导航栏的如图下面区域
鼠标移到这个区域看看有没有滚动条：

![169646582-ca5493e1-b901-4185-8399-80bd92f03b1e](https://user-images.githubusercontent.com/23169045/169649760-ac6b1e19-57d2-4a5e-8b77-4be5a786a214.png)

另外在靠下面的位置弹出浮窗时，可以双击浅灰浮窗标题栏，浮窗会钉住不消失，然后鼠标按住标题栏往上面拖动一下，让窗口变大一点以便查看更多内容

**Comment by mindstudy** [comment]
如果方便的话，可否把这一页打包一下上传到这里看看具体什么情况

具体文件位置是在：在文档树上的该文档右键--打开--打开文件位置，然后把定位到的那个****.sy文件copy出来，用winzip压缩一下上传到这里。

如果该文档可能存在不便分享的内容，打包前可用记事本一类的软件打开，删除相关内容后再压缩上传一下。

**Comment by bengirl2021** [comment]
> Mac系统下目前显示正常。
> 
> 可能是系统或浏览器内核的兼容问题，排查起来需要时日。

对，我是win10，那可能是兼容问题了，复现的话只要是比较长的内容都会出现这种状况，我就不导出了哈哈
![批注 2022-05-21 205844](https://user-images.githubusercontent.com/101393495/169652606-a6572e7e-b3f7-4c77-8a34-bf17691506b3.png)

**Comment by bengirl2021** [comment]
太喜欢你这个主题了，大哥有时间弄弄呗♥

**Comment by mindstudy** [comment]
肯定想办法搞定，放心哈。
刚才问了一位win系统的朋友，使用的是这里的最新版（比集市新），貌似滚动条显示正常，你先试试看

只需要覆盖对应明暗主题文件夹的 theme.css 就行

明色版：
https://github.com/mindstudy/siyuan-themes-concise-light/archive/refs/heads/main.zip
暗色版
https://github.com/mindstudy/siyuan-themes-concise-dark/archive/refs/heads/main.zip

**Comment by bengirl2021** [comment]
还是8行，我发现纯文档可以，但是无需列表不行



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月21日(周六) 晚上9:22
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [mindstudy/siyuan-themes-concise-light] 在鼠标放到引用的内容上，如果显示不全，不会出现滚动条 (Issue #10)




 
肯定想办法搞定，放心哈。
 刚才问了一位win系统的朋友，使用的是这里的最新版（比集市新），貌似滚动条显示正常，你先试试看
 
只需要覆盖对应明暗主题文件夹的 theme.css 就行
 
明色版：
 https://github.com/mindstudy/siyuan-themes-concise-light/archive/refs/heads/main.zip
 暗色版
 https://github.com/mindstudy/siyuan-themes-concise-dark/archive/refs/heads/main.zip

**Comment by mindstudy** [comment]
更新了代码，上面的链接重新下载覆盖看看

**Comment by bengirl2021** [comment]
可以了！，感谢
