### ISSUE TITLE
2.0.16版本后无法给块内长表格或代码添加滚动条了

### ISSUE THREAD

**Issue by hscui** [mindstudy/siyuan-themes-concise-light#11]
更新前我一直使用论坛上一个代码给块内长表格或代码添加滚动条，更新到2.0.16后这个代码失效了，能不能帮我看下是什么原因，谢谢。
代码见：https://ld246.com/article/1647693571588

**Comment by mindstudy** [comment]
看到你已经在那个贴搞定了。

下个版本加入这个功能，这样以后就不必自己修改代码了。

**Comment by hscui** [comment]
> 看到你已经在那个贴搞定了。
> 
> 下个版本加入这个功能，这样以后就不必自己修改代码了。

谢谢，主题挺好用的。

我都不懂CSS的，随便乱删结果能用了。
另外请教一下：我原本不想删除，但试着用/* */注释掉不要的部分，但思源刷新后依然保持原样；而DARK版本删除就能用了；所以我在Light版中也删除了，然后刷新就生效了。
思源在读取主题时是会把注释内的代码也读取了？

**Comment by mindstudy** [comment]
主题已提交集市，等官方通过。

不能马上刷新可能是缓存机制，可以看看这个帖后半部分有关缓存的讨论
https://github.com/mindstudy/siyuan-themes-concise-light/issues/6

**Comment by hscui** [comment]
> 

嗯，上次问的也是我；一直都用的你说的这种方法。

所以我觉得奇怪，感觉思源就不认注释，或者对于含有代码注释不认为是注释。

**Comment by mindstudy** [comment]
上次的方法应该能应付能想到的缓存问题了

要么就是跨行注释时，比如  /* （若干行） */  ，这个若干行里面有注释符号 /* 

css 貌似不支持跨行嵌套注释的，你再试试看

集市已OK，可以更新主题了
