### ISSUE TITLE
标题超过一行时会被下面文字覆盖

### ISSUE THREAD

**Issue by hscui** [mindstudy/siyuan-themes-concise-light#2]
标题文字过多，一行显示不下时，会被下面文字覆盖一半，希望能改进。
![image](https://user-images.githubusercontent.com/7949195/157381650-7c0543db-9a77-4b3b-b51f-254a83d135b2.png)

**Comment by mindstudy** [comment]
好的，这两天较忙，会尽快更改调整细节。

可先按下面的说明搜索修改一下应应急：

在主题目录的 theme.css 里搜索：
/* 层级标题折叠字号保持一致 */

将
`.protyle-content .protyle-wysiwyg .h1[fold="1"] {`
`.protyle-content .protyle-wysiwyg .h2[fold="1"] {`
`.protyle-content .protyle-wysiwyg .h3[fold="1"] {`

各自所属的3处 `    height: 32px;` 删除即可。

由于涉及折叠效果，细节会进一步完善。

**Comment by mindstudy** [comment]
主题上传更新有一定时间的等待期，下面涉及标题折叠的代码可先拿去用用。

搜索同样位置，将
.protyle-content .protyle-wysiwyg .h1[fold="1"] {
.protyle-content .protyle-wysiwyg .h2[fold="1"] {
.protyle-content .protyle-wysiwyg .h3[fold="1"] {
.protyle-content .protyle-wysiwyg .h4[fold="1"] {
.protyle-content .protyle-wysiwyg .h5[fold="1"] {
.protyle-content .protyle-wysiwyg .h6[fold="1"] {

各自所属的 
`    line-height: 1.25;`
改成：
`    line-height: 1.5;`

本问题修改将在 1.8.5 版本更新。

其他问题也欢迎提出，以便后续修改。

**Comment by hscui** [comment]
> 谢谢，已做修改。
> 
> 由于主题上传更新有一定时间的等待期，可先下载这边的 theme.css，然后覆盖下面位置的文件即可 Siyuan/conf/appearance/themes/Concise Light/theme.css

谢谢，我试试。
