### ISSUE TITLE
 文档标题的emoji问题求助

### ISSUE THREAD

**Issue by yunyq** [mindstudy/siyuan-themes-concise-light#3]
您好！十分喜欢主题清爽舒适。
主题中的标签emoji感觉不够突出，想换为原来的那种，捯饬了半天也没整明白，请教下如何修改。
![VeryCapture_20220316161903](https://user-images.githubusercontent.com/99524638/158550775-a530a144-dab2-44fc-949d-c79c656753c7.jpg)
![VeryCapture_20220316164242](https://user-images.githubusercontent.com/99524638/158550810-e47846f7-4fc1-4bc0-b1f6-02310c9b805f.jpg)

**Comment by mindstudy** [comment]
应该是字体的原因，改了一下，你下载附件先试试看

**Comment by mindstudy** [comment]
今天github貌似上传有点问题，如果看不到附件，告诉一下邮箱发给你

**Comment by mindstudy** [comment]
应该是字体问题，改了一下，可以打包下载一下最新版，先试试看
<img width="1027" alt="Screen Shot 2022-03-16 at 9 21 46 PM" src="https://user-images.githubusercontent.com/23169045/158599318-1e40fd15-5bb9-4c56-af0a-670c1ffc58c1.png">

**Comment by yunyq** [comment]
***@***.*** 谢谢您！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月16日(星期三) 晚上9:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mindstudy/siyuan-themes-concise-light]  文档标题的emoji问题求助 (Issue #3)





 
今天github貌似上传有点问题，如果看不到附件，告诉一下邮箱发给你
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
