### ISSUE TITLE
 任务列表时，字体设置失效

### ISSUE THREAD

**Issue by yunyq** [mindstudy/siyuan-themes-concise-light#4]
哈喽，俺又来啦
任务列表下，只能通过选中文字设置字体，而通过段落块或文档块设置字体无效。
并且，上一级是”任务“列表时，也会影响次级”无序“列表的字体
![image](https://user-images.githubusercontent.com/99524638/158777403-7e855573-72f3-4354-b2ef-15db50eb97e3.png)

**Comment by mindstudy** [comment]
可以试一下用自定义属性来设置整个段落属性，中间有说明如何操作
https://www.yuque.com/u25584857/ryp75p/sgf58w#DTlnI

属性名 z （文章里的老图是属性名zt）
属性名 
ht  黑体
kt 楷体
fs 仿宋

**Comment by yunyq** [comment]
有很多项任务时，想修改黑体为其他字体，发现只能通过选中文字一行一行来修改，不方便。
1、直接插入任务列表，设置段落属性，无效，还是黑体。
2、插入普通段落，设置段落属性，再转化为任务列表，字体得以保留，但增加次级任务列表时，还是黑体。
就感觉任务列表会使自定义属性的修改无效

https://user-images.githubusercontent.com/99524638/158924951-5500b72b-5749-4420-8aea-43d3d008d6f1.mp4

。

**Comment by mindstudy** [comment]
改了改，下载这边的最新版 theme.css 覆盖一下，试试看哈

**Comment by yunyq** [comment]
完美解决 感谢！
