### ISSUE TITLE
大佬，== 样式异常，换行的话会挤在一起。

### ISSUE THREAD

**Issue by roverway** [mindstudy/siyuan-themes-concise-light#5]
![image](https://user-images.githubusercontent.com/657850/158978254-1d90b1d3-216e-47dd-ad06-42063b6d80e4.png)
就像图里那样，希望可以更新下。

**Comment by mindstudy** [comment]
感谢反馈，改过来了

下载这边的 theme.css 覆盖一下试试看效果如何（集市更新需要等待）

**Comment by roverway** [comment]
好了，感谢大佬！
