### ISSUE TITLE
询问如何修改任务勾选为以前的方框

### ISSUE THREAD

**Issue by hscui** [mindstudy/siyuan-themes-concise-light#6]
如题，还是喜欢方框，不太喜欢目前是圆形点。

**Comment by mindstudy** [comment]
打开 Siyuan/conf/appearance/themes/Concise Light/theme.css
这个样式的代码位置在 /* 待办列表 */ 和 /* 弹出浮窗块引用 */内容之间
搜索：/* 待办列表 */
然后把/* 待办列表 */及以下的内容，删除到/* 弹出浮窗块引用 */之前，保存一下生效

如果没有生效，可点击思源笔记左上角那个小月牙图标（即切换到暗色模式），
然后再点击一次，切换回明色模式，更改后的 theme.css 即会刷新生效

**Comment by hscui** [comment]
> 打开 Siyuan/conf/appearance/themes/Concise Light/theme.css 这个样式的代码位置在` /* 待办列表 */` 和` /* 弹出浮窗块引用 */`内容之间 搜索：`/* 待办列表 */` 然后把`/* 待办列表 */`及以下的内容，删除到`/* 弹出浮窗块引用 */`之前，保存一下生效
> 
> 如果没有生效，可点击思源笔记左上角那个小月牙图标（即切换到暗色模式）， 然后再点击一次，切换回明色模式，更改后的 theme.css 即会刷新生效

收到，谢谢。

**Comment by mindstudy** [comment]
多半是缓存的原因，试一下这个：

Ctrl + Alt + i 打开开发者工具 （如果是Mac， Cmd+Alt+i）
然后点 Network，勾选 Disable Cache；
接着点 Console，在它的命令行窗口输入： `window.location.reload()`

页面会自动刷新



![custom-theme2-20210512172239-pcnzes0](https://user-images.githubusercontent.com/23169045/160535006-3f82eaba-1a5a-48af-a10e-36505d277a2e.png)


![custom-theme2-20210512172239-pcnzes0](https://user-images.githubusercontent.com/23169045/160534755-5b992280-40b4-4aa8-89ae-78e5945cc576.png)

**Comment by hscui** [comment]
> 多半是缓存的原因，试一下这个：
> 
> Ctrl + Alt + i 打开开发者工具 （如果是Mac， Cmd+Alt+i） 然后点 Network，勾选 Disable Cache； 接着点 Console，在它的命令行窗口输入： `window.location.reload()`
> 
> 页面会自动刷新
> 
> ![custom-theme2-20210512172239-pcnzes0](https://user-images.githubusercontent.com/23169045/160535006-3f82eaba-1a5a-48af-a10e-36505d277a2e.png)

谢谢，我也试了这个，依然没用。

最后的解决办法：删除此主题，然后重新从集市下载后再次将theme.css修改后刷新就可以了。

问题估计是出在思源的缓存上面，或者是火绒？

**Comment by mindstudy** [comment]
想起来思源还有一个缓存，以后遇到修改不生效问题（不一定是主题，比如说修改语言包）可以试试搜索 SiYuan-Electron 文件夹，然后删除 SiYuan-Electron/Cache 目录下的所有缓存文件

**Comment by hscui** [comment]
> 想起来思源还有一个缓存，以后遇到修改不生效问题（不一定是主题，比如说修改语言包）可以试试搜索 SiYuan-Electron 文件夹，然后删除 SiYuan-Electron/Cache 目录下的所有缓存文件

好的，再次感谢。
