### ISSUE TITLE
PDF浏览问题

### ISSUE THREAD

**Issue by yunyq** [mindstudy/siyuan-themes-concise-light#7]
大佬，如图，浏览PDF时能切换为正常颜色模式吗？

**Comment by yunyq** [comment]
![1](https://user-images.githubusercontent.com/99524638/163661653-73d8bd4c-ff12-47e7-8536-ebdd00839a4b.png)

**Comment by mindstudy** [comment]
更新了，下载这边的 theme.css 覆盖一下看看（集市更新较慢）

**Comment by yunyq** [comment]
解决了 谢谢！！！
