### ISSUE TITLE
字体加删除线的，则不显示

### ISSUE THREAD

**Issue by xy0124** [mindstudy/siyuan-themes-concise-light#8]
![image](https://user-images.githubusercontent.com/99000021/164617200-3052b94b-023f-4800-af5a-79d8f9b6c3cc.png)
如图

**Comment by mindstudy** [comment]
删除线设置为本主题的挖空复习功能，如果不需要可以按下面的说明恢复删除线：

https://www.yuque.com/u25584857/ryp75p/zlocwl#XuF9D
