### ISSUE TITLE
当鼠标箭头移动到任何段落块时，会高亮整个段落块

### ISSUE THREAD

**Issue by laoqiii** [mindstudy/siyuan-themes-concise-light#9]
这个主题是个人在市集里最喜欢的极简主题，但这个问题非常干扰使用体验，不知道其它人会不会有这种感受，可能是我有强迫症吧。如果作者能优化一下这个小问题就好了，这真的是我最喜欢的主题，谢谢！

**Comment by mindstudy** [comment]
谢谢反馈，设置为浅色高亮，是以前有用户提出的建议，为了便于一些定位操作。

可以很方便的去除这个特性，在主题文件夹 Concise Light 里打开 theme.css，搜索“当前块鼠标浮动高亮背景”

然后删除下面的语句即可：

`/* 当前块鼠标浮动高亮背景 */
.protyle-wysiwyg [data-node-id]:hover {
    background-color: #e9f0f9;
}`
